AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ThoughtsIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: thoughts-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Trust policy allowing the 866253333665 AWS account to assume this role
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::{AWSAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition: {}
          - Effect: Allow
            Principal:
              Service: 'bedrock.amazonaws.com'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWSAccountId
              ArnLike:
                'AWS:SourceArn': !Sub 'arn:aws:bedrock:*:{AWSAccountId}:knowledge-base/*'

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
